version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=trustvault
      - DB_USER=postgres
      - DB_PASSWORD=trustvaultpass
      - TOKENIZATION_API_URL=http://privacy-engine:5001
      - ANOMALY_DETECTION_API_URL=http://ml-service:5002
    depends_on:
      - postgres
      - privacy-engine
      - ml-service
    networks:
      - trustvault-network
    volumes:
      - ./backend:/app
      - /app/node_modules

  privacy-engine:
    build:
      context: ./privacy-engine
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - TOKENIZATION_SECRET_KEY=development-only-secret
    networks:
      - trustvault-network
    volumes:
      - ./privacy-engine:/app

  ml-service:
    build:
      context: ./ml-service
    ports:
      - "5002:5002"
    environment:
      - PORT=5002
      - ANOMALY_CONTAMINATION=0.1
    networks:
      - trustvault-network
    volumes:
      - ./ml-service:/app

  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=trustvault
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=trustvaultpass
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - trustvault-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
    depends_on:
      - backend
    networks:
      - trustvault-network
    volumes:
      - ./frontend:/app
      - /app/node_modules

networks:
  trustvault-network:
    driver: bridge

volumes:
  postgres-data:
